services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: NNPRO-employee-management
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
